---
- name: Fetch and Save Job Data
  hosts: localhost
  gather_facts: no
  vars:
    base_url: '{{ base_url }}'
    job_api_url: '/api/v2/unified_jobs/?or__type=job&or__type=workflow_job'
    headers:
      Authorization: '{{ bearer_token }}'
    job_output_file: 'ansible_job_report.csv'
    separator: '|'
    jobs_next_url: "{{ base_url }}{{ job_api_url }}"

  tasks:
    - name: Initialize the CSV file with headers
      copy:
        dest: "{{ job_output_file }}"
        content: |
          JOB_ID|JOB_TEMPLATE_ID|JOB_TEMPLATE_TYPE|LAUNCH_TYPE|START_DATE|END_DATE|STATUS

    - name: Debug jobs_next_url before initial request
      debug:
        msg: "Initial jobs_next_url: {{ jobs_next_url }}"

    # - name: Fetch and write job data - initial request
      # uri:
      #   url: "{{ jobs_next_url }}"
      #   headers: "{{ headers }}"
      #   return_content: yes
      #   validate_certs: no
      # register: response

    - name: Write job data to CSV - initial request
      lineinfile:
        dest: "{{ job_output_file }}"
        line: "{{ job.id }}|{{ job.unified_job_template }}|{{ job.type }}|{{ job.launch_type }}|{{ job.started }}|{{ job.finished }}|{{ job.status }}"
      with_items: "{{ response.json.results }}"
      when: response.json.results is defined and response.json.results | length > 0
      loop_control:
        loop_var: job
      ignore_errors: yes

    # - name: Set jobs_next_url for next request
    #   set_fact:
    #     jobs_next_url: "{{ response.json.next }}"

    - name: Debug jobs_next_url after initial request
      debug:
        msg: "jobs_next_url after initial request: {{ jobs_next_url }}"

    - name: Fetch and write job data - loop
      block:
        - name: Fetch next page of job data
          uri:
            url: "{{ jobs_next_url }}"
            headers: "{{ headers }}"
            return_content: yes
            validate_certs: no
          register: response_page
          when: jobs_next_url is defined and jobs_next_url != "null"

        - name: Write job data to CSV - next pages
          lineinfile:
            dest: "{{ job_output_file }}"
            line: "{{ job.id }}|{{ job.unified_job_template }}|{{ job.type }}|{{ job.launch_type }}|{{ job.started }}|{{ job.finished }}|{{ job.status }}"
          with_items: "{{ response_page.json.results }}"
          when: response_page.json.results is defined and response_page.json.results | length > 0
          loop_control:
            loop_var: job
          ignore_errors: yes
        # - name: Set jobs_next_url for next request - loop
        #   set_fact:
        #     jobs_next_url: "{{ response_page.json.next }}"
        #   when: response_page.json.next is defined and response_page.json.next != "null"
        #   until: jobs_next_url is not defined or jobs_next_url == "null"
        #   retries: 10
        #   delay: 2

        - name: Debug jobs_next_url in loop
          debug:
            msg: "jobs_next_url in loop: {{ jobs_next_url }}"

    - name: Display output file location
      debug:
        msg: "Data written to {{ job_output_file }}"

    - name: Copy file over SSH
      copy:
        src: "{{ job_output_file }}"
        dest: "{{remote_path}}{{ job_output_file }}"
      delegate_to: "{{ remote_host }}"
      become: yes
      vars:
        ansible_ssh_user: "{{ remote_user }}"
        ansible_ssh_pass: "{{ remote_password }}"
        ansible_become_pass: "{{ become_password }}"