---
- name: Gather job data and template data from API and write to CSV
  hosts: localhost
  gather_facts: no
  vars:
    headers:
      Authorization: "{{ bearer_token }}"
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
    output_folder: "{{ base_output_folder }}_{{ timestamp }}/"
    job_csv_headers:
      - 'JOB_ID'
      - 'JOB_TEMPLATE_ID'
      - 'JOB_TEMPLATE_TYPE'
      - 'LAUNCH_TYPE'
      - 'START_DATE'
      - 'END_DATE'
      - 'STATUS'
    template_csv_headers:
      - 'ORGANIZATION_NAME'
      - 'ORGANIZATION_DESCRIPTION'
      - 'TEMPLATE_ID'
      - 'TEMPLATE_TYPE'
      - 'TEMPLATE_NAME'
      - 'TEMPLATE_DESCRIPTION'
      - 'TEMPLATE_CREATED_BY'
      - 'TEMPLATE_CREATION_DATE'
      - 'TEMPLATE_EDIT_DATE'
      - 'PLAYBOOK'
      - 'HAS_SURVEY'
      - 'PROJECT_ID'
      - 'PROJECT_NAME'
      - 'PROJECT_DESCRIPTION'
      - 'TOTAL_EXECUTED_JOBS'
      - 'LAST_JOB_RUN'
      - 'LAST_JOB_FAILED'
      - 'NEXT_JOB_RUN'
  tasks:
    # Date and folders
    - name: Include tasks Prepare Environment
      include_tasks: tasks/01.prepare-environment.yml

    # JOB_TEMPLATES
    - name: Include tasks JOB_TEMPLATES
      include_tasks: tasks/02.job-templates.yml

    ## Remote Directory
    - name: Include tasks REMOTE_FILE_TRANSFER
      include_tasks: tasks/04.remote-directories.yml