---
- name: Process Dynamic Survey and Set combo2
  hosts: localhost
  tasks:
    - name: Generate hostnames
      command: python3 ../scripts/02.dummydata.py 
      register: generated_hosts
      changed_when: false

    - name: Prepare survey spec with auto-selected combo2
      set_fact:
        survey_spec: {
          "name": "Dynamic Survey Based on Host Selection",
          "description": "Select options as per your requirements",
          "spec": [
            {
              "question_name": "host_selection",
              "question_description": "Choose a host:",
              "required": true,
              "type": "multiplechoice",
              "variable": "host_selection",
              "default": "host1.example.com",
              "choices": "{{ generated_hosts.stdout | from_json }}" 
            },
            {
              "question_name": "os",
              "question_description": "Choose an os",
              "required": true,
              "type": "text",
              "variable": "os",
              "default": ""
            }
          ]
        }

    - name: Update survey in Ansible Tower
      ansible.controller.job_template:
        name: "Prepopulated Survey"
        survey_enabled: true
        survey_spec: "{{ survey_spec }}"
      environment:
        TOWER_HOST: "{{ tower_host }}"
        TOWER_OAUTH_TOKEN: "{{ tower_token }}"
      delegate_to: localhost
      when: survey_spec is defined

